### ISSUE TITLE
Move slonik to peerDependencies

### ISSUE THREAD

**Issue by nonara** [gajus/slonik-sql-tag-raw#7]
First -thanks for your great work! Really happy with slonik!

I have a setup as follows:

```
core (includes DB component)
   dependencies: 
      - slonik v23.0.1
      - slonik-sql-tag-raw v1.0.2

main (uses DB component)
   dependencies:
      - core
   peerDependencies:
      - slonik v23.0.1
```

The `main` package and many others include `core`. We use peerDependencies so that we can be sure that we use a single version of slonik.

When we use the DB component from `core` in another package, we import error classes from `slonik` to catch results.

Using this setup, I did a yarn install of the `main` package, and I encountered a problem where `NotFoundError` did not match the imported class.

What happened was `slonik-sql-tag-raw` uses slonik v22.4.4, as a `dependency`. So this caused the peer copy of of slonik installed to v22.4.4, and `core` installs its own copy in `node_modules`.

A solution for this would be to use [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) with a greater than version 

ie. `"peerDependencies": { "slonik": ">=22.0.0" }`

For testing, you can add a fixed version in `devDependencies`
